### ISSUE TITLE
override API endpoint with alpha url

### ISSUE THREAD

**Issue by lfallet** [googleapis/nodejs-video-intelligence#251]
**Is your feature request related to a problem? Please describe.**
I've been lucky enough to be enrolled in alpha testing of a new video intelligence feature.
I'd like to keep my current code, and point it to the alpha endpoint in order to test the feature.

**Describe the solution you'd like**
API endpoint is set here: https://github.com/googleapis/nodejs-video-intelligence/blob/d2e3563c20c8941ad9f91b582a59983cbaa480b7/src/v1/video_intelligence_service_client.js#L180
Having a `useAlphaEndpoint()` method on the client would be great. The method would use the endpoint `alpha-videointelligence.googleapis.com`

 **Describe alternatives you've considered**
Forking the lib and setting the `alpha-` url myself. However I would lose further updates of this lib.

**Comment by JustinBeckwith** [comment]
Greetings!  Good news is that with `2.1.0`, you can do that! Can you give this a try?

```js
const {VideoIntelligenceServiceClient} = require('@google-cloud/video-intelligence');
const client = new VideoIntelligenceServiceClient({
  apiEndpoint: 'alpha-videointelligence.googleapis.com'
});
```
