### ISSUE TITLE
sample tests failing

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/nodejs-video-intelligence#294]
[recent logs](https://source.cloud.google.com/results/invocations/a1a5d11d-d83d-4637-b811-73aeae97d5dc/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-video-intelligence%2Fnode10%2Fsamples-test/log)

**Comment by alexander-fenster** [comment]
They work now.
