### ISSUE TITLE
Passing multiple features in a request does not produce desired functionality

### ISSUE THREAD

**Issue by andy-hayes1** [googleapis/nodejs-video-intelligence#472]
#### Environment details

  - OS: Mac
  - Node.js version: 14.0.0
  - npm version: 6.14.4
  - `@google-cloud/video-intelligence` version: 3.0.1

I am currently building a custom library to implement google video intelligence and I am running into a bottleneck. I want to access multiple features of google video intelligence without having to make multiple requests with the same video.
 i.e. I am trying to build my requests and pass multiple feature names in an array like so:
`{
    inputContent: inputContent,
    locationId: locationId,
    features: ['OBJECT_TRACKING', 'SPEECH_TRANSCRIPTION'],
    videoContext: {
      speechTranscriptionConfig: {
        languageCode: 'en-US',
        enableAutomaticPunctuation: true
      }
    }
`

When I do this, I do not get either object tracking annotations or speech transcription, but rather a response with empty arrays. However, when I pass only one of the features at a time the api works as expected and I get either object tracking or speech transcription. This is slightly problematic because I want to utilize both features without having to add the computational cost of sending the same video multiple times. Is this a feature that is currently supported?

#### Steps to reproduce

  1. Pass multiple features in feature array when making a request

**Comment by munkhuushmgl** [comment]
@telpirion Do you know if this feature is feasible or not?

**Comment by vinnysenthil** [comment]
Closing this issue as the thread has been inactive for over a year. Please re-open if this is still an active issue.
